<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CKN.Sdk.Search\CKN.Sdk.Search.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Meilisearch" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

</Project>
