<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Moq" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CKN.Sdk.Core\CKN.Sdk.Core.csproj" />
    <ProjectReference Include="..\CKN.Sdk.Infrastructure\CKN.Sdk.Infrastructure.csproj" />
    <ProjectReference Include="..\CKN.Sdk.Messaging\CKN.Sdk.Messaging.csproj" />
    <ProjectReference Include="..\CKN.Sdk.Messaging.Kafka\CKN.Sdk.Messaging.Kafka.csproj" />
    <ProjectReference Include="..\CKN.Sdk.Data.Dapper\CKN.Sdk.Data.Dapper.csproj" />
    <ProjectReference Include="..\CKN.Sdk.Caching.Garnet\CKN.Sdk.Caching.Garnet.csproj" />
    <ProjectReference Include="..\CKN.Sdk.AI.OpenAI\CKN.Sdk.AI.OpenAI.csproj" />
    <ProjectReference Include="..\CKN.Sdk.AI.Anthropic\CKN.Sdk.AI.Anthropic.csproj" />
    <ProjectReference Include="..\CKN.Sdk.Storage.Minio\CKN.Sdk.Storage.Minio.csproj" />
    <ProjectReference Include="..\CKN.Sdk.Storage.Azure\CKN.Sdk.Storage.Azure.csproj" />
  </ItemGroup>

</Project>