<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CKN.Sdk.Storage\CKN.Sdk.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Minio" />
  </ItemGroup>

  <PropertyGroup>
    
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
