<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CKN.Sdk.Core\CKN.Sdk.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OllamaSharp" ExcludeAssets="analyzers" />
  </ItemGroup>

  <PropertyGroup>
    
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS9057</NoWarn>
    <RunAnalyzers>false</RunAnalyzers>
  </PropertyGroup>

</Project>
