<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CKN.Sdk.Core\CKN.Sdk.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OllamaSharp" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
