using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CKN.Sdk.SourceGenerators
{
    [Generator]
    public class CknHandlerGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                    transform: (ctx, _) => GetClassWithIRequestHandler(ctx))
                .Where(x => x != null);

            context.RegisterSourceOutput(provider.Collect(), (ctx, source) =>
            {
                var classes = source.Distinct().ToList();
                if (classes.Count == 0) return;

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
                sb.AppendLine();
                sb.AppendLine("namespace CKN.Sdk.Generated");
                sb.AppendLine("{");
                sb.AppendLine("    public static class HandlerRegistrationExtensions");
                sb.AppendLine("    {");
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// AOT-compatible registration of all CQRS handlers in the assembly.");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        public static IServiceCollection AddCknGeneratedHandlers(this IServiceCollection services)");
                sb.AppendLine("        {");

                foreach (var item in classes)
                {
                    foreach (var iface in item.Value.InterfaceNames)
                    {
                        sb.AppendLine($"            services.AddTransient<{iface}, {item.Value.ClassName}>();");
                    }
                }

                sb.AppendLine("            return services;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");

                ctx.AddSource("CknHandlerRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            });
        }

        private static ClassInfo? GetClassWithIRequestHandler(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
            
            if (symbol == null || symbol.IsAbstract) return null;

            var interfaces = symbol.AllInterfaces
                .Where(i => i.Name == "IRequestHandler" || i.Name == "ICommandHandler" || i.Name == "IQueryHandler")
                .Select(i => i.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .ToList();

            if (interfaces.Count > 0)
            {
                return new ClassInfo
                {
                    ClassName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    InterfaceNames = interfaces
                };
            }

            return null;
        }

        private struct ClassInfo
        {
            public string ClassName;
            public List<string> InterfaceNames;
        }
    }
}
