<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CKN.Sdk.Core\CKN.Sdk.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.Core" />
  </ItemGroup>

  <PropertyGroup>
    
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
